"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _scoreboard_list from './scoreboard-list.bones.json'

registerBones({
  "scoreboard-list": _scoreboard_list,
})
