// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provee sobrescrituras de tema en runtime vía contexto de React.
// Envuelve un subárbol en <PdfxThemeProvider theme={myTheme}> para sobrescribir valores por defecto.

// Intencional: este módulo exporta tanto componente como hooks/context.
// Mantener una sola superficie de import preserva la API pública generada.

import { type DependencyList, type ReactNode, createContext, useContext } from 'react';
import { theme as defaultTheme } from './pdfx-theme';

type PdfxTheme = typeof defaultTheme;

export const PdfxThemeContext = createContext<PdfxTheme>(defaultTheme);

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme;
  children: ReactNode;
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = theme ?? defaultTheme;
  return <PdfxThemeContext.Provider value={resolvedTheme}>{children}</PdfxThemeContext.Provider>;
}

/**
 * Devuelve el tema activo desde el contexto.
 *
 * Cuando se llama fuera de un árbol de render de React (por ejemplo, en pruebas de funciones simples),
 * React puede lanzar un error de hook inválido. En ese caso devolvemos defaultTheme.
 * Los errores inesperados se vuelven a lanzar.
 */
export function usePdfxTheme(): PdfxTheme {
  return useContext(PdfxThemeContext);
}

/**
 * Ejecuta factory() y devuelve el resultado.
 * El parámetro deps se acepta para mantener compatibilidad de API con llamadas existentes.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory();
}
